-- OM Power Solutions Supabase Schema

-- 1. Projects Table
CREATE TABLE IF NOT EXISTS public.projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  category TEXT NOT NULL,
  location TEXT NOT NULL,
  capacity TEXT NOT NULL,
  year INTEGER NOT NULL,
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Services Table
CREATE TABLE IF NOT EXISTS public.services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  icon TEXT,
  image_url TEXT,
  color TEXT DEFAULT 'blue',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Products Table
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  description TEXT,
  specs TEXT NOT NULL,
  brochure_url TEXT,
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Careers Table
CREATE TABLE IF NOT EXISTS public.careers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  location TEXT NOT NULL,
  type TEXT NOT NULL,
  exp TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Inquiries Table
CREATE TABLE IF NOT EXISTS public.inquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  subject TEXT,
  message TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Set up Row Level Security (RLS) policies

-- Projects: Anyone can read, only admin can write
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read access" ON public.projects FOR SELECT USING (true);
CREATE POLICY "Admin write access" ON public.projects FOR ALL USING (auth.role() = 'authenticated');

-- Services: Anyone can read, only admin can write
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read access" ON public.services FOR SELECT USING (true);
CREATE POLICY "Admin write access" ON public.services FOR ALL USING (auth.role() = 'authenticated');

-- Products: Anyone can read, only admin can write
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read access" ON public.products FOR SELECT USING (true);
CREATE POLICY "Admin write access" ON public.products FOR ALL USING (auth.role() = 'authenticated');

-- Careers: Anyone can read, only admin can write
ALTER TABLE public.careers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read access" ON public.careers FOR SELECT USING (true);
CREATE POLICY "Admin write access" ON public.careers FOR ALL USING (auth.role() = 'authenticated');

-- Inquiries: Anyone can insert, only admin can read/write
ALTER TABLE public.inquiries ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public insert access" ON public.inquiries FOR INSERT WITH CHECK (true);
CREATE POLICY "Admin read/write access" ON public.inquiries FOR ALL USING (auth.role() = 'authenticated');

-- 6. Partner Inquiries Table
CREATE TABLE IF NOT EXISTS public.partner_inquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  company_name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  location TEXT NOT NULL,
  partnership_type TEXT NOT NULL,
  message TEXT,
  status TEXT DEFAULT 'Pending' NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.partner_inquiries ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public insert access" ON public.partner_inquiries FOR INSERT WITH CHECK (true);
CREATE POLICY "Admin read/write access" ON public.partner_inquiries FOR ALL USING (auth.role() = 'authenticated');

-- 7. Testimonials Table
CREATE TABLE IF NOT EXISTS public.testimonials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_name TEXT NOT NULL,
  company TEXT,
  testimonial TEXT NOT NULL,
  rating INTEGER DEFAULT 5,
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read access" ON public.testimonials FOR SELECT USING (true);
CREATE POLICY "Admin write access" ON public.testimonials FOR ALL USING (auth.role() = 'authenticated');
